logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  endpoint:
    health:
      probes:
        enabled: true
  tracing:
    sampling:
      probability: 1.0

server:
  error:
    include-binding-errors: on-param
    include-message: on-param
    whitelabel:
      enabled: false

spring:
  application:
    name: fulfillment-orders
  datasource:
    url: jdbc:h2:mem:fulfillment-orders
  flyway:
    sql-migration-prefix: h2-v-
  h2:
    console:
      settings:
        web-allow-others: true
  web:
    resources:
      add-mappings: false
